# Site settings
title: Beautystrap
email: danilobjr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://danilojr.azurewebsites.net" # the base hostname & protocol for your site
twitter_username: danilojrr
github_username:  danilojrr

# Build settings
markdown: kramdown

# Configurations
host: localhost
port: 3000